const ROLE_CONFIG = {
  super_admin: {
    label: 'SaaS Super Admin',
    permissions: {
      manageTenants: true,
      manageGlobalCalendar: true,
      viewFinancialTotals: true,
      viewReports: true,
      overrideBlocks: true,
      manageDevotees: true,
      viewDevoteeDirectory: true,
      logDonations: true,
      generateReceipts: true,
      cancelOrRefund: true,
      manageInventory: true,
      viewInventory: true,
      manageSchedule: true,
      viewSchedule: true,
      manageWhatsApp: true,
      runCron: true,
      approveSensitiveActions: true,
      manageSetup: true,
      importExportData: true,
      managePayments: true,
      reconcilePayments: true,
      accessDevoteePortal: true,
      manageExpenses: true,
      viewAccounting: true,
      manageEvents: true,
      managePublicContent: true,
      manageGlobalLibrary: true,
      viewNetworkVihar: true,
      manageStaffUsers: true,
    },
  },
  trustee: {
    label: 'Mandir Trustee',
    permissions: {
      manageTenants: false,
      manageGlobalCalendar: false,
      viewFinancialTotals: true,
      viewReports: true,
      overrideBlocks: true,
      manageDevotees: true,
      viewDevoteeDirectory: true,
      logDonations: true,
      generateReceipts: true,
      cancelOrRefund: true,
      manageInventory: true,
      viewInventory: true,
      manageSchedule: true,
      viewSchedule: true,
      manageWhatsApp: true,
      runCron: true,
      approveSensitiveActions: true,
      manageSetup: true,
      importExportData: true,
      managePayments: true,
      reconcilePayments: true,
      accessDevoteePortal: true,
      manageExpenses: true,
      viewAccounting: true,
      manageEvents: true,
      managePublicContent: true,
      manageGlobalLibrary: false,
      viewNetworkVihar: true,
      manageStaffUsers: true,
    },
  },
  admin: {
    label: 'Munim / Accountant (Admin)',
    permissions: {
      manageTenants: false,
      manageGlobalCalendar: false,
      viewFinancialTotals: false,
      viewReports: true,
      overrideBlocks: false,
      manageDevotees: true,
      viewDevoteeDirectory: true,
      logDonations: true,
      generateReceipts: true,
      cancelOrRefund: true,
      manageInventory: true,
      viewInventory: true,
      manageSchedule: true,
      viewSchedule: true,
      manageWhatsApp: true,
      runCron: true,
      approveSensitiveActions: false,
      manageSetup: false,
      importExportData: true,
      managePayments: true,
      reconcilePayments: true,
      accessDevoteePortal: true,
      manageExpenses: true,
      viewAccounting: true,
      manageEvents: true,
      managePublicContent: true,
      manageGlobalLibrary: false,
      viewNetworkVihar: true,
      manageStaffUsers: true,
    },
  },
  executive: {
    label: 'Sevadar / Volunteer (Executive)',
    permissions: {
      manageTenants: false,
      manageGlobalCalendar: false,
      viewFinancialTotals: false,
      viewReports: false,
      overrideBlocks: false,
      manageDevotees: false,
      viewDevoteeDirectory: true,
      logDonations: false,
      generateReceipts: false,
      cancelOrRefund: false,
      manageInventory: false,
      viewInventory: false,
      manageSchedule: false,
      viewSchedule: true,
      manageWhatsApp: false,
      runCron: false,
      approveSensitiveActions: false,
      manageSetup: false,
      importExportData: false,
      managePayments: false,
      reconcilePayments: false,
      accessDevoteePortal: true,
      manageExpenses: false,
      viewAccounting: false,
      manageEvents: false,
      managePublicContent: false,
      manageGlobalLibrary: false,
      viewNetworkVihar: false,
      manageStaffUsers: false,
    },
  },
}

function getPermissionsForRole(role) {
  return ROLE_CONFIG[role]?.permissions || {}
}

module.exports = {
  ROLE_CONFIG,
  getPermissionsForRole,
}
